model_path: "../../res_b5/Net_0"
num_executor: 3
num_task: 150
devices: ["lynxi"]

input_files: "../../resnet/data/tank"

batch_size: 5

inputs:
  - shape: [5, 3, 224, 224]
    dtype: float32

outputs:
  - shape: [5,1000]
    dtype: float32


# 注意input shape和 output shape的batch size要一致